<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DemoMApplicationsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('m_applications')->delete();

        \DB::table('m_applications')->insert(array (
            0 =>
                array (
                    'id' => 1,
                    'name' => 'PASTEL',
                    'description' => '<p>Administrative management</p>',
                    'security_need_c' => 3,
                    'responsible' => 'Margaret Hamilton',
                    'type' => 'logiciel',
                    'technology' => 'PHP',
                    'external' => NULL,
                    'users' => '> 50',
                    'created_at' => '2020-06-14 11:20:15',
                    'updated_at' => '2022-03-20 18:53:29',
                    'deleted_at' => NULL,
                    'entity_resp_id' => 1,
                    'application_block_id' => 1,
                    'documentation' => '//Documentation/pastel.docx',
                    'security_need_i' => 3,
                    'security_need_a' => 4,
                    'security_need_t' => 3,
                    'version' => '3.5',
                    'functional_referent' => 'Dr. A. Smith',
                    'editor' => 'MedTech Co.',
                    'install_date' => '2019-01-15',
                    'update_date' => '2023-05-10',
                    'rto' => '4 hours',
                    'rpo' => '1 hour',
                    'vendor' => 'MedTech Co.',
                    'product' => 'PASTEL',
                    'maturity' => 4,
                ),
            1 =>
                array (
                    'id' => 2,
                    'name' => 'APTA',
                    'description' => '<p>Quality assessment</p>',
                    'security_need_c' => 2,
                    'responsible' => 'Margaret Hamilton',
                    'type' => 'logiciel',
                    'technology' => 'Java',
                    'external' => NULL,
                    'users' => '> 20',
                    'created_at' => '2020-06-14 11:20:15',
                    'updated_at' => '2022-03-20 18:53:29',
                    'deleted_at' => NULL,
                    'entity_resp_id' => 1,
                    'application_block_id' => 2,
                    'documentation' => '//Documentation/apta.docx',
                    'security_need_i' => 2,
                    'security_need_a' => 3,
                    'security_need_t' => 2,
                    'version' => '2.1',
                    'functional_referent' => 'Dr. B. Johnson',
                    'editor' => 'QualiSoft Inc.',
                    'install_date' => '2018-06-20',
                    'update_date' => '2022-10-15',
                    'rto' => '6 hours',
                    'rpo' => '2 hours',
                    'vendor' => 'QualiSoft Inc.',
                    'product' => 'APTA',
                    'maturity' => 2,
                ),
            2 =>
                array (
                    'id' => 3,
                    'name' => 'Cariatides',
                    'description' => '<p>Medical file management</p>',
                    'security_need_c' => 5,
                    'responsible' => 'Margaret Hamilton',
                    'type' => 'logiciel',
                    'technology' => 'Python',
                    'external' => NULL,
                    'users' => '> 100',
                    'created_at' => '2020-06-14 11:20:15',
                    'updated_at' => '2022-03-20 18:53:29',
                    'deleted_at' => NULL,
                    'entity_resp_id' => 1,
                    'application_block_id' => 3,
                    'documentation' => '//Documentation/cariatides.docx',
                    'security_need_i' => 5,
                    'security_need_a' => 5,
                    'security_need_t' => 5,
                    'version' => '4.0',
                    'functional_referent' => 'Dr. C. Lee',
                    'editor' => 'HealthSoft Ltd.',
                    'install_date' => '2020-03-10',
                    'update_date' => '2023-01-12',
                    'rto' => '2 hours',
                    'rpo' => '30 minutes',
                    'vendor' => 'HealthSoft Ltd.',
                    'product' => 'Cariatides',
                    'maturity' => 5,
                ),
            3 =>
                array (
                    'id' => 4,
                    'name' => 'SOLON',
                    'description' => '<p>Public procurements management</p>',
                    'security_need_c' => 3,
                    'responsible' => 'Margaret Hamilton',
                    'type' => 'logiciel',
                    'technology' => 'Ruby on Rails',
                    'external' => NULL,
                    'users' => '> 10',
                    'created_at' => '2020-06-14 11:20:15',
                    'updated_at' => '2022-03-20 18:53:29',
                    'deleted_at' => NULL,
                    'entity_resp_id' => 1,
                    'application_block_id' => 4,
                    'documentation' => '//Documentation/solon.docx',
                    'security_need_i' => 3,
                    'security_need_a' => 3,
                    'security_need_t' => 3,
                    'version' => '1.8',
                    'functional_referent' => 'Mr. D. White',
                    'editor' => 'EconSoft LLC',
                    'install_date' => '2017-09-25',
                    'update_date' => '2021-11-20',
                    'rto' => '8 hours',
                    'rpo' => '2 hours',
                    'vendor' => 'EconSoft LLC',
                    'product' => 'SOLON',
                    'maturity' => 4,
                ),
            4 =>
                array (
                    'id' => 5,
                    'name' => 'AutoCAD',
                    'description' => '<p>Plan management</p>',
                    'security_need_c' => 2,
                    'responsible' => 'Margaret Hamilton',
                    'type' => 'logiciel',
                    'technology' => 'Autodesk',
                    'external' => NULL,
                    'users' => '> 15',
                    'created_at' => '2020-06-14 11:20:15',
                    'updated_at' => '2022-03-20 18:53:29',
                    'deleted_at' => NULL,
                    'entity_resp_id' => 1,
                    'application_block_id' => 5,
                    'documentation' => '//Documentation/autocad.docx',
                    'security_need_i' => 2,
                    'security_need_a' => 2,
                    'security_need_t' => 2,
                    'version' => '2021',
                    'functional_referent' => 'Ms. E. Green',
                    'editor' => 'Autodesk',
                    'install_date' => '2019-11-11',
                    'update_date' => '2023-02-20',
                    'rto' => '12 hours',
                    'rpo' => '4 hours',
                    'vendor' => 'Autodesk',
                    'product' => 'AutoCAD',
                    'maturity' => 3,
                ),
            5 =>
                array (
                    'id' => 6,
                    'name' => 'AGIRH',
                    'description' => '<p>Human Resources management</p>',
                    'security_need_c' => 3,
                    'responsible' => 'Margaret Hamilton',
                    'type' => 'logiciel',
                    'technology' => 'JavaScript',
                    'external' => NULL,
                    'users' => '> 30',
                    'created_at' => '2020-06-14 11:20:15',
                    'updated_at' => '2022-03-20 18:53:29',
                    'deleted_at' => NULL,
                    'entity_resp_id' => 1,
                    'application_block_id' => 6,
                    'documentation' => '//Documentation/agirh.docx',
                    'security_need_i' => 3,
                    'security_need_a' => 3,
                    'security_need_t' => 3,
                    'version' => '5.3',
                    'functional_referent' => 'Ms. F. Brown',
                    'editor' => 'HRSoft',
                    'install_date' => '2016-08-19',
                    'update_date' => '2021-12-05',
                    'rto' => '6 hours',
                    'rpo' => '1 hour',
                    'vendor' => 'HRSoft',
                    'product' => 'AGIRH',
                    'maturity' => 4,
                ),
            6 =>
                array (
                    'id' => 7,
                    'name' => 'AGIRH Planning',
                    'description' => '<p>Human Resources planning</p>',
                    'security_need_c' => 3,
                    'responsible' => 'Margaret Hamilton',
                    'type' => 'logiciel',
                    'technology' => 'JavaScript',
                    'external' => NULL,
                    'users' => '> 30',
                    'created_at' => '2020-06-14 11:20:15',
                    'updated_at' => '2022-03-20 18:53:29',
                    'deleted_at' => NULL,
                    'entity_resp_id' => 1,
                    'application_block_id' => 6,
                    'documentation' => '//Documentation/agirh_planning.docx',
                    'security_need_i' => 3,
                    'security_need_a' => 3,
                    'security_need_t' => 3,
                    'version' => '3.7',
                    'functional_referent' => 'Ms. F. Brown',
                    'editor' => 'HRSoft',
                    'install_date' => '2016-08-19',
                    'update_date' => '2021-12-05',
                    'rto' => '6 hours',
                    'rpo' => '1 hour',
                    'vendor' => 'HRSoft',
                    'product' => 'AGIRH Planning',
                    'maturity' => 4,
                ),
            7 =>
                array (
                    'id' => 8,
                    'name' => 'PH7',
                    'description' => '<p>Salary management</p>',
                    'security_need_c' => 3,
                    'responsible' => 'Margaret Hamilton',
                    'type' => 'logiciel',
                    'technology' => 'C#',
                    'external' => NULL,
                    'users' => '> 25',
                    'created_at' => '2020-06-14 11:20:15',
                    'updated_at' => '2022-03-20 18:53:29',
                    'deleted_at' => NULL,
                    'entity_resp_id' => 1,
                    'application_block_id' => 7,
                    'documentation' => '//Documentation/ph7.docx',
                    'security_need_i' => 3,
                    'security_need_a' => 4,
                    'security_need_t' => 3,
                    'version' => '2.9',
                    'functional_referent' => 'Mr. G. Johnson',
                    'editor' => 'PaySoft Ltd.',
                    'install_date' => '2018-04-15',
                    'update_date' => '2022-08-10',
                    'rto' => '4 hours',
                    'rpo' => '2 hours',
                    'vendor' => 'PaySoft Ltd.',
                    'product' => 'PH7',
                    'maturity' => 4,
                ),
            8 =>
                array (
                    'id' => 9,
                    'name' => 'CHIMED',
                    'description' => '<p>Occupational medicine management</p>',
                    'security_need_c' => 3,
                    'responsible' => 'Margaret Hamilton',
                    'type' => 'logiciel',
                    'technology' => 'Python',
                    'external' => NULL,
                    'users' => '> 20',
                    'created_at' => '2020-06-14 11:20:15',
                    'updated_at' => '2022-03-20 18:53:29',
                    'deleted_at' => NULL,
                    'entity_resp_id' => 1,
                    'application_block_id' => 8,
                    'documentation' => '//Documentation/chimed.docx',
                    'security_need_i' => 3,
                    'security_need_a' => 3,
                    'security_need_t' => 3,
                    'version' => '1.5',
                    'functional_referent' => 'Dr. H. Davis',
                    'editor' => 'HealthSoft Ltd.',
                    'install_date' => '2018-12-01',
                    'update_date' => '2023-03-05',
                    'rto' => '6 hours',
                    'rpo' => '2 hours',
                    'vendor' => 'HealthSoft Ltd.',
                    'product' => 'CHIMED',
                    'maturity' => 4,
                ),
            9 =>
                array (
                    'id' => 10,
                    'name' => 'Apache',
                    'description' => '<p>Intranet management</p>',
                    'security_need_c' => 2,
                    'responsible' => 'Margaret Hamilton',
                    'type' => 'logiciel',
                    'technology' => 'Apache',
                    'external' => NULL,
                    'users' => '> 50',
                    'created_at' => '2020-06-14 11:20:15',
                    'updated_at' => '2022-03-20 18:53:29',
                    'deleted_at' => NULL,
                    'entity_resp_id' => 1,
                    'application_block_id' => 9,
                    'documentation' => '//Documentation/apache.docx',
                    'security_need_i' => 2,
                    'security_need_a' => 2,
                    'security_need_t' => 2,
                    'version' => '2.4.46',
                    'functional_referent' => 'Mr. J. Black',
                    'editor' => 'Apache Software Foundation',
                    'install_date' => '2017-05-01',
                    'update_date' => '2021-09-15',
                    'rto' => '12 hours',
                    'rpo' => '4 hours',
                    'vendor' => 'Apache Software Foundation',
                    'product' => 'Apache HTTP Server',
                    'maturity' => 3,
                ),
            10 =>
                array (
                    'id' => 11,
                    'name' => 'IIS',
                    'description' => '<p>Extranet management</p>',
                    'security_need_c' => 2,
                    'responsible' => 'Margaret Hamilton',
                    'type' => 'logiciel',
                    'technology' => 'Microsoft',
                    'external' => NULL,
                    'users' => '> 50',
                    'created_at' => '2020-06-14 11:20:15',
                    'updated_at' => '2022-03-20 18:53:29',
                    'deleted_at' => NULL,
                    'entity_resp_id' => 1,
                    'application_block_id' => 10,
                    'documentation' => '//Documentation/iis.docx',
                    'security_need_i' => 2,
                    'security_need_a' => 2,
                    'security_need_t' => 2,
                    'version' => '10.0',
                    'functional_referent' => 'Mr. J. Black',
                    'editor' => 'Microsoft',
                    'install_date' => '2017-05-01',
                    'update_date' => '2021-09-15',
                    'rto' => '12 hours',
                    'rpo' => '4 hours',
                    'vendor' => 'Microsoft',
                    'product' => 'Internet Information Services',
                    'maturity' => 1,
                ),
        ));
    }
}